const BASE_APP_URL = process.env.NEXT_PUBLIC_BASE_APP_URL;
const ACCESS_TOKEN_COOKIE_KEY = process.env.NEXT_PUBLIC_ACCESS_TOKEN_COOKIE_KEY;
const REFRESH_TOKEN_COOKIE_KEY = process.env.NEXT_PUBLIC_REFRESH_TOKEN_COOKIE_KEY;
const USER_SESSION_COOKIE_KEY = process.env.NEXT_PUBLIC_USER_SESSION_COOKIE_KEY;

export { ACCESS_TOKEN_COOKIE_KEY, BASE_APP_URL, REFRESH_TOKEN_COOKIE_KEY, USER_SESSION_COOKIE_KEY };
